image: docker:stable

# services:
    #- docker:dind

variables:
  CONTAINER_IMAGE: git.lug.ustc.edu.cn/$CI_PROJECT_PATH
  CONTAINER_BRANCH_IMAGE: git.lug.ustc.edu.cn/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME
  #DOCKER_HOST: tcp://docker:2375
  #DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD git.lug.ustc.edu.cn

build:
  stage: build
  script:
    - docker pull $CONTAINER_BRANCH_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_BRANCH_IMAGE:latest --tag $CONTAINER_BRANCH_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_BRANCH_IMAGE:latest .
    - docker push $CONTAINER_BRANCH_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_BRANCH_IMAGE:latest
    #- docker build --tag admin-server:$CI_COMMIT_SHA --tag admin-server:latest ./
